org: saichann
app: aws-discord-bot
service: discord-bot

provider:
  name: aws
  stage: ${opt:stage, "develop"}
  region: ${opt:region, "ap-northeast-1"}
  ecr:
    images:
      core:
        path: ./
  # Lambda関連
  # architecture: arm64
  runtime: python3.11
  memorySize: 128
  timeout: 120
  versionFunctions: true
  maximumRetryAttempts: 0
  iam:
    role: LambdaExecutionRole
  # デプロイ用S3バケット設定
  deploymentBucket:
    name: ${self:service}-${opt:stage, "develop"}-deployment-bucket-${aws:accountId}
  # X-Rayトレース設定
  tracing:
    apiGateway: true
    lambda: true
  tags:
    Project: ${self:service}
    Create: ServerlessFramework
  # resources部のタグ設定
  stackTags:
    Project: ${self:service}
    Create: ServerlessFramework
  environment:
    VERSION: "1.0.0"
    TZ: Asia/Tokyo
    RESOURCE_NAME_PREFIX: ${param:resourceNamePrefix}
    APPLICATION_ID: ${env:APPLICATION_ID}
    DISCORD_PUBLIC_KEY: ${env:DISCORD_PUBLIC_KEY}
    BOT_TOKEN: ${env:BOT_TOKEN}

# plugins:
#   - serverless-prune-plugin
#   - serverless-offline

# custom:
# prune:
#   automatic: true
#   number: 3

params:
  develop:
    resourceNamePrefix: ${self:service}-develop
  production:
    resourceNamePrefix: ${self:service}

functions:
  router:
    name: ${param:resourceNamePrefix}-router
    url: true
    memorySize: 4096
    timeout: 10
    image:
      name: core
      command:
        - src.router.main.lambda_handler
  updateSlashCommand:
    name: ${param:resourceNamePrefix}-update-slash-command
    memorySize: 128
    image:
      name: core
      command:
        - src.common.update_slash_command.lambda_handler
    events:
      - schedule:
          rate: rate(10 minutes)
          enabled: true
  dog:
    name: ${param:resourceNamePrefix}-dog
    image:
      name: core
      command:
        - src.commands.dog.lambda_handler
  ncodice:
    name: ${param:resourceNamePrefix}-ncodice
    image:
      name: core
      command:
        - src.commands.ncodice.lambda_handler
  dailyNcodice:
    name: ${param:resourceNamePrefix}-daily_ncodice
    image:
      name: core
      command:
        - src.tasks.daily_ncodice.lambda_handler
    events:
      - schedule:
          rate: cron(0 0 ? * * *)
          enabled: true

resources:
  - ${file(./cloudformation/iam.yml)}
