name: CD
run-name: Deploy ${{ github.ref_name }} branch to ${{ inputs.environment }} environment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "デプロイ環境"
        required: true
        type: environment
        default: develop

jobs:
  deploy:
    concurrency: deploy_concurrency_${{ inputs.environment }}
    name: Deploy ${{ inputs.environment }}

    environment:
      name: ${{ inputs.environment }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - run: npm ci

      - name: serverless deploy
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
        run: npx serverless deploy --verbose --stage=${{ inputs.environment }}
